### PR TITLE
Handle possible new line in device name

### PR DESCRIPTION
**Pull request by XMadFoX**
I did helper function to replace all (or most) special characters which can cause new line in device name
Not sure about structure, maybe util.c should be moved to /common or /utils directory

I'm not sure if device_name even used somewhere in GUI 🤔 

#21

### CODE REVIEW

**Comment by AlynxZhou** [comment]
> I'm not sure if device_name even used somewhere in GUI 

It's not used in GUI.

I think maybe it's better to escape `\n` to things like `\\n`, so it's still the same char in json.

And maybe just move the function into main.c, we don't use it anywhere.

Or just simply remove `device_name` from JSON.

**Comment by XMadFoX** [comment]
@AlynxZhou and do you plan to use it in GUI?

If not, well... yeah, I think it should be just removed.

**Comment by AlynxZhou** [comment]
> @AlynxZhou and do you plan to use it in GUI?
> 
> If not, well... yeah, I think it should be just removed.

Currently No, I'll remove it, thanks.

**Comment by AlynxZhou** [comment]
Not a problem now.

**Pull request closed without merging**
